# Gitleaks configuration for Adobe A2B Agency
title = "Adobe A2B Agency Secret Detection"

# Custom rules for Adobe-specific credentials
[[rules]]
id = "adobe-openwhisk-auth"
description = "Adobe OpenWhisk/I/O Runtime Authentication Token"
regex = '''["']?auth["']?\s*:\s*["']?[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}:[A-Za-z0-9+/]{40,}={0,2}["']?'''
tags = ["adobe", "openwhisk", "auth"]

[[rules]]
id = "adobe-auth-base64"
description = "Adobe Base64 Authentication String"
regex = '''["']?(auth|authorization|token|api[_-]?key)["']?\s*[:=]\s*["']?[A-Za-z0-9+/]{40,}={0,2}["']?'''
tags = ["adobe", "auth", "api-key"]
[rules.allowlist]
stopwords = ["FAKE", "TEST", "EXAMPLE", "SAMPLE", "PLACEHOLDER", "MOCK", "XXX"]

[allowlist]
description = "Allow FAKE values and test files for Adobe A2B Agency"
# Only allow specific documentation paths, not all JSON files
paths = [
    "docs/apis/list-events/.*\\.json$",  # API documentation samples only
    "docs/events/.*\\.json$",             # Event documentation samples only
    ".*\\.md$",                           # Markdown documentation
    "README.*",                           # README files
]

regexes = [
    # Allow AEM_AUTH_CLIENT_SECRET with FAKE values
    '''AEM_AUTH_CLIENT_SECRET\s*=\s*["']?.*FAKE.*["']?\s*$''',
    
    # Allow AEM_AUTH_CLIENT_SECRET in JSON with FAKE values
    '''"AEM_AUTH_CLIENT_SECRET"\s*:\s*["']?.*FAKE.*["']?\s*[,}]''',
    
    # Allow S2S_API_KEY with FAKE values
    '''"S2S_API_KEY"\s*:\s*["']?.*fake.*["']?\s*[,}]''',
    
    # Allow S2S_CLIENT_SECRET with FAKE values
    '''"S2S_CLIENT_SECRET"\s*:\s*["']?.*fake.*["']?\s*[,}]''',
    
    # Allow AEM_AUTH_PRIVATE_KEY with FAKE values
    '''"AEM_AUTH_PRIVATE_KEY"\s*:\s*["']?.*FAKE.*["']?\s*[,}]''',
    
    # Allow standardized fake private key format
    '''-----BEGIN RSA PRIVATE KEY-----\\nFAKE\\n-----END RSA PRIVATE KEY-----''',
    
    # Allow FAKE values for testing
    '''["']?.*FAKE.*_FOR_TESTING_ONLY["']?\s*[,}]''',
    
    # Allow test patterns
    '''["']?.*(FAKE|TEST|EXAMPLE|SAMPLE).*["']?\s*[,}]''',
    
    # Allow empty secret values
    '''(CLIENT_SECRET|API_KEY|PRIVATE_KEY)\s*[:=]\s*["']?["']?\s*[,}]?$''',
    
    # Allow "secret" as a field name in JSON documentation
    '''"(optional|required)Fields"\s*:\s*\[[^\]]*"secret"[^\]]*\]''',
    
    # Allow field name "secret" in JSON arrays
    '''["']secret["']\s*[,\]]'''
]

stopwords = [
    "FAKE",
    "TEST", 
    "EXAMPLE",
    "SAMPLE",
    "PLACEHOLDER",
    "MOCK"
]