# Gitleaks configuration for Adobe A2B Agency
title = "Adobe A2B Agency Secret Detection"

[allowlist]
description = "Allow FAKE values and test files for Adobe A2B Agency"
paths = [
    "docs/.*",
    ".*\\.md$",
    ".*\\.json$",
    ".*\\.env.*",
    ".*\\.ya?ml$",
    ".*\\.config\\..*",
    ".*test.*",
    ".*example.*",
    ".*sample.*"
]

regexes = [
    # Allow AEM_AUTH_CLIENT_SECRET with FAKE values
    '''AEM_AUTH_CLIENT_SECRET\s*=\s*["']?.*FAKE.*["']?\s*$''',
    
    # Allow AEM_AUTH_CLIENT_SECRET in JSON with FAKE values
    '''"AEM_AUTH_CLIENT_SECRET"\s*:\s*["']?.*FAKE.*["']?\s*[,}]''',
    
    # Allow S2S_API_KEY with FAKE values
    '''"S2S_API_KEY"\s*:\s*["']?.*fake.*["']?\s*[,}]''',
    
    # Allow S2S_CLIENT_SECRET with FAKE values
    '''"S2S_CLIENT_SECRET"\s*:\s*["']?.*fake.*["']?\s*[,}]''',
    
    # Allow AEM_AUTH_PRIVATE_KEY with FAKE values
    '''"AEM_AUTH_PRIVATE_KEY"\s*:\s*["']?.*FAKE.*["']?\s*[,}]''',
    
    # Allow standardized fake private key format
    '''-----BEGIN RSA PRIVATE KEY-----\\nFAKE\\n-----END RSA PRIVATE KEY-----''',
    
    # Allow FAKE values for testing
    '''["']?.*FAKE.*_FOR_TESTING_ONLY["']?\s*[,}]''',
    
    # Allow test patterns
    '''["']?.*(FAKE|TEST|EXAMPLE|SAMPLE).*["']?\s*[,}]''',
    
    # Allow empty secret values
    '''(CLIENT_SECRET|API_KEY|PRIVATE_KEY)\s*[:=]\s*["']?["']?\s*[,}]?$''',
    
    # Allow "secret" as a field name in JSON documentation
    '''"(optional|required)Fields"\s*:\s*\[[^\]]*"secret"[^\]]*\]''',
    
    # Allow field name "secret" in JSON arrays
    '''["']secret["']\s*[,\]]'''
]

stopwords = [
    "FAKE",
    "TEST", 
    "EXAMPLE",
    "SAMPLE",
    "PLACEHOLDER",
    "MOCK"
]