application:
  actions: src/actions
  runtimeManifest:
    packages:
      test-debugger:
        license: Apache-2.0
        actions:
          asset-event-handler:
            function: src/actions/asset-event-handler/index.ts
            web: 'yes'
            runtime: nodejs:18
            inputs:
              LOG_LEVEL: debug
            annotations:
              require-adobe-auth: false
              final: true
extensions:
  dx/excshell/1:
    $include: src/dx-excshell-1/ext.config.yaml