application:
  actions: src/actions
  runtimeManifest:
    packages:
      a2b-agency:
        license: Apache-2.0
        actions:
          assetsync-event-handler:
            function: src/actions/assetsync-event-handler/index.ts
            web: 'yes'
            runtime: nodejs:20
            inputs:
              LOG_LEVEL: debug
              ORG_ID: $ORG_ID
              AIO_AGENCY_EVENTS_AEM_ASSET_SYNC_PROVIDER_ID: $AIO_AGENCY_EVENTS_AEM_ASSET_SYNC_PROVIDER_ID
              AEM_AUTH_CLIENT_SECRET: $AEM_AUTH_CLIENT_SECRET
              AEM_AUTH_SCOPES: $AEM_AUTH_SCOPES
              S2S_CLIENT_ID: $SERVICE_API_KEY
              S2S_CLIENT_SECRET: $S2S_CLIENT_SECRET
              S2S_SCOPES: $S2S_SCOPES
            annotations:
              require-adobe-auth: true
              final: true
          new-brand-registration:
            function: src/actions/new-brand-registration/index.ts
            web: 'yes'
            runtime: nodejs:20
            inputs:
              LOG_LEVEL: debug
              ORG_ID: $ORG_ID
              S2S_API_KEY: $SERVICE_API_KEY
              AIO_AGENCY_EVENTS_REGISTRATION_PROVIDER_ID: $AIO_AGENCY_EVENTS_REGISTRATION_PROVIDER_ID
              S2S_CLIENT_ID: $SERVICE_API_KEY
              S2S_CLIENT_SECRET: $S2S_CLIENT_SECRET
              S2S_SCOPES: $S2S_SCOPES
            annotations:
              require-adobe-auth: false
              final: true
          get-brands:
            function: src/actions/get-brands/index.ts
            web: 'yes'
            runtime: nodejs:20
            inputs:
              LOG_LEVEL: debug
            annotations:
              require-adobe-auth: true
              final: true
          delete-brand:
            function: src/actions/delete-brand/index.ts
            web: 'yes'
            runtime: nodejs:20
            inputs:
              LOG_LEVEL: debug
              S2S_CLIENT_ID: $SERVICE_API_KEY
              S2S_CLIENT_SECRET: $S2S_CLIENT_SECRET
              S2S_SCOPES: $S2S_SCOPES
              ORG_ID: $ORG_ID
              AIO_AGENCY_EVENTS_REGISTRATION_PROVIDER_ID: $AIO_AGENCY_EVENTS_REGISTRATION_PROVIDER_ID
            annotations:
              require-adobe-auth: true
              final: true
extensions:
  dx/excshell/1:
    $include: src/dx-excshell-1/ext.config.yaml