application:
  actions: src/actions
  runtimeManifest:
    packages:
      a2b-agency:
        license: Apache-2.0
        actions:
          asset-event-handler:
            function: src/actions/asset-event-handler/index.ts
            web: 'yes'
            runtime: nodejs:20
            inputs:
              LOG_LEVEL: debug
            annotations:
              require-adobe-auth: false
              final: true
          new-brand-registration:
            function: src/actions/new-brand-registration/index.ts
            web: 'yes'
            runtime: nodejs:20
            inputs:
              LOG_LEVEL: debug
            annotations:
              require-adobe-auth: false
              final: true
          get-brands:
            function: src/actions/get-brands/index.ts
            web: 'yes'
            runtime: nodejs:20
            inputs:
              LOG_LEVEL: debug
            annotations:
              require-adobe-auth: false
              final: true
extensions:
  dx/excshell/1:
    $include: src/dx-excshell-1/ext.config.yaml