application:
  actions: src/actions
  runtimeManifest:
    packages:
      a2b-agency:
        license: Apache-2.0
        actions:
          new-brand-registration:
            function: src/actions/services/brand/new-brand-registration/index.ts
            web: 'yes'
            runtime: nodejs:22
            inputs:
              LOG_LEVEL: debug
              ORG_ID: $ORG_ID
              AGENCY_ID: $AGENCY_ID
              AGENCY_NAME: $AGENCY_NAME
              S2S_API_KEY: $SERVICE_API_KEY
              AIO_AGENCY_EVENTS_BRAND_REGISTRATION_PROVIDER_ID: $AIO_AGENCY_EVENTS_BRAND_REGISTRATION_PROVIDER_ID
              AIO_AGENCY_EVENTS_AEM_ASSET_SYNC_PROVIDER_ID: $AIO_AGENCY_EVENTS_AEM_ASSET_SYNC_PROVIDER_ID
              S2S_CLIENT_ID: $SERVICE_API_KEY
              S2S_CLIENT_SECRET: $S2S_CLIENT_SECRET
              S2S_SCOPES: $S2S_SCOPES
              AIO_RUNTIME_APIHOST: $AIO_runtime_apihost
              AIO_RUNTIME_AUTH: $AIO_runtime_auth
              AIO_RUNTIME_NAMESPACE: $AIO_runtime_namespace
              APPLICATION_RUNTIME_INFO: '{"namespace":"${AIO_runtime_namespace}","app_name":"agency","action_package_name":"${AIO_ACTION_PACKAGE_NAME}"}'
            annotations:
              require-adobe-auth: false
              final: true
          get-brands:
            function: src/actions/services/brand/get-brands/index.ts
            web: 'yes'
            runtime: nodejs:22
            inputs:
              LOG_LEVEL: debug
              APPLICATION_RUNTIME_INFO: '{"namespace":"${AIO_runtime_namespace}","app_name":"agency","action_package_name":"${AIO_ACTION_PACKAGE_NAME}"}'
            annotations:
              require-adobe-auth: true
              final: true
          get-brand:
            function: src/actions/services/brand/get-brand/index.ts
            web: 'yes'
            runtime: nodejs:22
            inputs:
              LOG_LEVEL: debug
              APPLICATION_RUNTIME_INFO: '{"namespace":"${AIO_runtime_namespace}","app_name":"agency","action_package_name":"${AIO_ACTION_PACKAGE_NAME}"}'
            annotations:
              require-adobe-auth: true
              final: true
          list-product-events:
            function: src/actions/services/event-registry/product/list-product-events/index.ts
            web: 'yes'
            runtime: nodejs:22
            inputs:
              LOG_LEVEL: debug
            annotations:
              require-adobe-auth: true
              final: true
          delete-brand:
            function: src/actions/services/brand/delete-brand/index.ts
            web: 'yes'
            runtime: nodejs:22
            inputs:
              LOG_LEVEL: debug
              S2S_CLIENT_ID: $SERVICE_API_KEY
              S2S_CLIENT_SECRET: $S2S_CLIENT_SECRET
              S2S_SCOPES: $S2S_SCOPES
              AGENCY_ID: $AGENCY_ID
              ORG_ID: $ORG_ID
              APPLICATION_RUNTIME_INFO: '{"namespace":"${AIO_runtime_namespace}","app_name":"agency","action_package_name":"${AIO_ACTION_PACKAGE_NAME}"}'
            annotations:
              require-adobe-auth: true
              final: true
          list-workfront-companies:
            function: src/actions/services/workfront/list-workfront-companies/index.ts
            web: 'yes'
            runtime: nodejs:22
            inputs:
              LOG_LEVEL: debug
              S2S_CLIENT_ID: $SERVICE_API_KEY
              S2S_CLIENT_SECRET: $S2S_CLIENT_SECRET
              S2S_SCOPES: $S2S_SCOPES
              ORG_ID: $ORG_ID
            annotations:
              require-adobe-auth: true
              final: true
          list-workfront-groups:
            function: src/actions/services/workfront/list-workfront-groups/index.ts
            web: 'yes'
            runtime: nodejs:22
            inputs:
              LOG_LEVEL: debug
              S2S_CLIENT_ID: $SERVICE_API_KEY
              S2S_CLIENT_SECRET: $S2S_CLIENT_SECRET
              S2S_SCOPES: $S2S_SCOPES
              ORG_ID: $ORG_ID
            annotations:
              require-adobe-auth: true
              final: true
          configure-workfront:
            function: src/actions/services/workfront/configure-workfront/index.ts
            web: 'yes'
            runtime: nodejs:22
            inputs:
              LOG_LEVEL: debug
              APPLICATION_RUNTIME_INFO: '{"namespace":"${AIO_runtime_namespace}","app_name":"agency","action_package_name":"${AIO_ACTION_PACKAGE_NAME}"}'
            annotations:
              require-adobe-auth: true
              final: true
          manage-workfront-subscriptions:
            function: src/actions/services/workfront/manage-workfront-subscriptions/index.ts
            web: 'no'
            runtime: nodejs:22
            inputs:
              LOG_LEVEL: debug
              S2S_CLIENT_ID: $SERVICE_API_KEY
              S2S_CLIENT_SECRET: $S2S_CLIENT_SECRET
              S2S_SCOPES: $S2S_SCOPES
              ORG_ID: $ORG_ID
              APPLICATION_RUNTIME_INFO: '{"namespace":"${AIO_runtime_namespace}","app_name":"agency","action_package_name":"${AIO_ACTION_PACKAGE_NAME}"}'
            annotations:
              require-adobe-auth: false
              final: true
          brand-event-handler:
            function: src/actions/event-handlers/brand-event-handler/index.ts
            web: 'yes'
            runtime: nodejs:22
            inputs:
              LOG_LEVEL: debug
              AIO_RUNTIME_APIHOST: $AIO_runtime_apihost
              AIO_RUNTIME_AUTH: $AIO_runtime_auth
              AIO_RUNTIME_NAMESPACE: $AIO_runtime_namespace
              APPLICATION_RUNTIME_INFO: '{"namespace":"${AIO_runtime_namespace}","app_name":"agency","action_package_name":"${AIO_ACTION_PACKAGE_NAME}"}'
            annotations:
              require-adobe-auth: false
              final: true
          adobe-product-event-handler:
            function: src/actions/event-handlers/product/adobe-product-event-handler/index.ts
            web: 'no'
            runtime: nodejs:22
            inputs:
              LOG_LEVEL: debug
            annotations:
              require-adobe-auth: false
              final: true
          agency-assetsync-internal-handler-process-complete:
            function: src/actions/event-handlers/product/agency-assetsync-internal-handler-process-complete/index.ts
            web: 'no'
            runtime: nodejs:22
            inputs:
              LOG_LEVEL: debug
              ADOBE_INTERNAL_URL_ENDPOINT: $ADOBE_INTERNAL_URL_ENDPOINT
              ORG_ID: $ORG_ID
              S2S_API_KEY: $SERVICE_API_KEY
              S2S_CLIENT_ID: $SERVICE_API_KEY
              S2S_CLIENT_SECRET: $S2S_CLIENT_SECRET
              S2S_SCOPES: $S2S_SCOPES
              AIO_RUNTIME_APIHOST: $AIO_runtime_apihost
              AIO_RUNTIME_AUTH: $AIO_runtime_auth
              AIO_RUNTIME_NAMESPACE: $AIO_runtime_namespace
              APPLICATION_RUNTIME_INFO: '{"namespace":"${AIO_runtime_namespace}","app_name":"agency","action_package_name":"${AIO_ACTION_PACKAGE_NAME}"}'
              AEM_AUTH_TYPE: $AEM_AUTH_TYPE
              AEM_AUTH_CLIENT_ID: $AEM_AUTH_CLIENT_ID
              AEM_AUTH_CLIENT_SECRET: $AEM_AUTH_CLIENT_SECRET
              AEM_AUTH_TECH_ACCOUNT_ID: $AEM_AUTH_TECH_ACCOUNT_ID
              AEM_AUTH_SCOPES: $AEM_AUTH_SCOPES
              AEM_AUTH_PRIVATE_KEY: $AEM_AUTH_PRIVATE_KEY
              AIO_AGENCY_EVENTS_AEM_ASSET_SYNC_PROVIDER_ID: $AIO_AGENCY_EVENTS_AEM_ASSET_SYNC_PROVIDER_ID
              AIO_AGENCY_EVENTS_BRAND_REGISTRATION_PROVIDER_ID: $AIO_AGENCY_EVENTS_BRAND_REGISTRATION_PROVIDER_ID
            annotations:
              require-adobe-auth: false
              final: true
          agency-assetsync-internal-handler-metadata-updated:
            function: src/actions/event-handlers/product/agency-assetsync-internal-handler-metadata-updated/index.ts
            web: 'no'
            runtime: nodejs:22
            inputs:
              LOG_LEVEL: debug
              ADOBE_INTERNAL_URL_ENDPOINT: $ADOBE_INTERNAL_URL_ENDPOINT
              ORG_ID: $ORG_ID
              S2S_API_KEY: $SERVICE_API_KEY
              S2S_CLIENT_ID: $SERVICE_API_KEY
              S2S_CLIENT_SECRET: $S2S_CLIENT_SECRET
              S2S_SCOPES: $S2S_SCOPES
              AIO_RUNTIME_APIHOST: $AIO_runtime_apihost
              AIO_RUNTIME_AUTH: $AIO_runtime_auth
              AIO_RUNTIME_NAMESPACE: $AIO_runtime_namespace
              APPLICATION_RUNTIME_INFO: '{"namespace":"${AIO_runtime_namespace}","app_name":"agency","action_package_name":"${AIO_ACTION_PACKAGE_NAME}"}'
              AEM_AUTH_TYPE: $AEM_AUTH_TYPE
              AEM_AUTH_CLIENT_ID: $AEM_AUTH_CLIENT_ID
              AEM_AUTH_CLIENT_SECRET: $AEM_AUTH_CLIENT_SECRET
              AEM_AUTH_TECH_ACCOUNT_ID: $AEM_AUTH_TECH_ACCOUNT_ID
              AEM_AUTH_SCOPES: $AEM_AUTH_SCOPES
              AEM_AUTH_PRIVATE_KEY: $AEM_AUTH_PRIVATE_KEY
              AIO_AGENCY_EVENTS_AEM_ASSET_SYNC_PROVIDER_ID: $AIO_AGENCY_EVENTS_AEM_ASSET_SYNC_PROVIDER_ID
              AIO_AGENCY_EVENTS_BRAND_REGISTRATION_PROVIDER_ID: $AIO_AGENCY_EVENTS_BRAND_REGISTRATION_PROVIDER_ID
            annotations:
              require-adobe-auth: false
              final: true
          update-brand:
            function: src/actions/services/brand/update-brand/index.ts
            web: 'yes'
            runtime: nodejs:22
            inputs:
              LOG_LEVEL: debug
              S2S_CLIENT_ID: $SERVICE_API_KEY
              S2S_CLIENT_SECRET: $S2S_CLIENT_SECRET
              S2S_SCOPES: $S2S_SCOPES
              AGENCY_ID: $AGENCY_ID
              AGENCY_NAME: $AGENCY_NAME
              ORG_ID: $ORG_ID
              APPLICATION_RUNTIME_INFO: '{"namespace":"${AIO_runtime_namespace}","app_name":"agency","action_package_name":"${AIO_ACTION_PACKAGE_NAME}"}'
            annotations:
              require-adobe-auth: true
              final: true
          list-app-events:
            function: src/actions/services/event-registry/app/list-app-events/index.ts
            web: 'yes'
            runtime: nodejs:22
            inputs:
              LOG_LEVEL: debug
            annotations:
              require-adobe-auth: true
              final: true
          get-app-event:
            function: src/actions/services/event-registry/app/get-app-event/index.ts
            web: 'yes'
            runtime: nodejs:22
            inputs:
              LOG_LEVEL: debug
            annotations:
              require-adobe-auth: true
              final: true
          get-product-event:
            function: src/actions/services/event-registry/product/get-product-event/index.ts
            web: 'yes'
            runtime: nodejs:22
            inputs:
              LOG_LEVEL: debug
            annotations:
              require-adobe-auth: true
              final: true
          list-product-routing-rules:
            function: src/actions/services/routing-rules/global/product/list-product-routing-rules/index.ts
            web: 'yes'
            runtime: nodejs:22
            inputs:
              LOG_LEVEL: debug
            annotations:
              require-adobe-auth: true
              final: true
          get-product-routing-rules:
            function: src/actions/services/routing-rules/global/product/get-product-routing-rules/index.ts
            web: 'yes'
            runtime: nodejs:22
            inputs:
              LOG_LEVEL: debug
            annotations:
              require-adobe-auth: true
              final: true
          create-product-routing-rule:
            function: src/actions/services/routing-rules/global/product/create-product-routing-rule/index.ts
            web: 'yes'
            runtime: nodejs:22
            inputs:
              LOG_LEVEL: debug
            annotations:
              require-adobe-auth: true
              final: true
          update-product-routing-rule:
            function: src/actions/services/routing-rules/global/product/update-product-routing-rule/index.ts
            web: 'yes'
            runtime: nodejs:22
            inputs:
              LOG_LEVEL: debug
            annotations:
              require-adobe-auth: true
              final: true
          delete-product-routing-rule:
            function: src/actions/services/routing-rules/global/product/delete-product-routing-rule/index.ts
            web: 'yes'
            runtime: nodejs:22
            inputs:
              LOG_LEVEL: debug
            annotations:
              require-adobe-auth: true
              final: true
          list-app-routing-rules:
            function: src/actions/services/routing-rules/global/app/list-app-routing-rules/index.ts
            web: 'yes'
            runtime: nodejs:22
            inputs:
              LOG_LEVEL: debug
            annotations:
              require-adobe-auth: true
              final: true
          get-app-routing-rules:
            function: src/actions/services/routing-rules/global/app/get-app-routing-rules/index.ts
            web: 'yes'
            runtime: nodejs:22
            inputs:
              LOG_LEVEL: debug
            annotations:
              require-adobe-auth: true
              final: true
          create-app-routing-rule:
            function: src/actions/services/routing-rules/global/app/create-app-routing-rule/index.ts
            web: 'yes'
            runtime: nodejs:22
            inputs:
              LOG_LEVEL: debug
            annotations:
              require-adobe-auth: true
              final: true
          update-app-routing-rule:
            function: src/actions/services/routing-rules/global/app/update-app-routing-rule/index.ts
            web: 'yes'
            runtime: nodejs:22
            inputs:
              LOG_LEVEL: debug
            annotations:
              require-adobe-auth: true
              final: true
          delete-app-routing-rule:
            function: src/actions/services/routing-rules/global/app/delete-app-routing-rule/index.ts
            web: 'yes'
            runtime: nodejs:22
            inputs:
              LOG_LEVEL: debug
            annotations:
              require-adobe-auth: true
              final: true
          list-brand-routing-rules:
            function: src/actions/services/routing-rules/brand/list-brand-routing-rules/index.ts
            web: 'yes'
            runtime: nodejs:22
            inputs:
              LOG_LEVEL: debug
            annotations:
              require-adobe-auth: true
              final: true
          get-brand-routing-rules:
            function: src/actions/services/routing-rules/brand/get-brand-routing-rules/index.ts
            web: 'yes'
            runtime: nodejs:22
            inputs:
              LOG_LEVEL: debug
            annotations:
              require-adobe-auth: true
              final: true
          create-brand-routing-rule:
            function: src/actions/services/routing-rules/brand/create-brand-routing-rule/index.ts
            web: 'yes'
            runtime: nodejs:22
            inputs:
              LOG_LEVEL: debug
            annotations:
              require-adobe-auth: true
              final: true
          update-brand-routing-rule:
            function: src/actions/services/routing-rules/brand/update-brand-routing-rule/index.ts
            web: 'yes'
            runtime: nodejs:22
            inputs:
              LOG_LEVEL: debug
            annotations:
              require-adobe-auth: true
              final: true
          delete-brand-routing-rule:
            function: src/actions/services/routing-rules/brand/delete-brand-routing-rule/index.ts
            web: 'yes'
            runtime: nodejs:22
            inputs:
              LOG_LEVEL: debug
            annotations:
              require-adobe-auth: true
              final: true
extensions:
  dx/excshell/1:
    $include: src/dx-excshell-1/ext.config.yaml
