name: Branch Protection Setup

on:
  workflow_dispatch:
  schedule:
    # Run weekly to ensure protection rules are maintained
    - cron: '0 0 * * 0'

jobs:
  setup-protection:
    name: Setup Branch Protection
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Setup Branch Protection
        uses: actions/github-script@v7
        with:
          script: |
            const { data: branches } = await github.rest.repos.listBranches({
              owner: context.repo.owner,
              repo: context.repo.repo
            });
            
            const mainBranch = branches.find(b => b.name === 'main') || branches.find(b => b.name === 'master');
            
            if (mainBranch) {
              console.log(`Setting up protection for branch: ${mainBranch.name}`);
              
              try {
                await github.rest.repos.updateBranchProtection({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  branch: mainBranch.name,
                  required_status_checks: {
                    strict: true,
                    contexts: ['test']
                  },
                  enforce_admins: false,
                  required_pull_request_reviews: {
                    required_approving_review_count: 1,
                    dismiss_stale_reviews: true,
                    require_code_owner_reviews: false
                  },
                  restrictions: null,
                  allow_force_pushes: false,
                  allow_deletions: false
                });
                
                console.log(`✅ Branch protection rules set for ${mainBranch.name}`);
              } catch (error) {
                console.log(`⚠️ Could not set branch protection: ${error.message}`);
                console.log('This might be due to insufficient permissions or the branch already being protected');
              }
            } else {
              console.log('❌ No main or master branch found');
            }
